### ISSUE TITLE
小米4.4.4手机运行不了

### ISSUE THREAD

**Issue by Lxiaoqiang** [youlookwhat/CloudReader#17]
02-09 09:14:27.437 9294-9294/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.jingbin.cloudreader, PID: 9294
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.jingbin.cloudreader/com.example.jingbin.cloudreader.ui.TransitionActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2190)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5047)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
                                                     at android.content.res.Resources.loadDrawable(Resources.java:2120)
                                                     at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:320)
                                                     at android.content.res.Resources.getDrawable(Resources.java:710)
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                     at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723)
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
                                                     at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                                                     at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                     at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                     at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
                                                     at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
                                                     at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
                                                     at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
                                                     at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
                                                     at com.example.jingbin.cloudreader.ui.TransitionActivity.onCreate(TransitionActivity.java:29)
                                                     at android.app.Activity.performCreate(Activity.java:5249)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5047) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                     at android.content.res.Resources.loadDrawable(Resources.java:2116)
                                                     at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:320) 
                                                     at android.content.res.Resources.getDrawable(Resources.java:710) 
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200) 
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188) 
                                                     at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723) 
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193) 
                                                     at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81) 
                                                     at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147) 
                                                     at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27) 
                                                     at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53) 
                                                     at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205) 
                                                     at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185) 
                                                     at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525) 
                                                     at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74) 
                                                     at com.example.jingbin.cloudreader.ui.TransitionActivity.onCreate(TransitionActivity.java:29) 
                                                     at android.app.Activity.performCreate(Activity.java:5249) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5047) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622) 
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by youlookwhat** [comment]
好，等下回公司我再测测

**Comment by youlookwhat** [comment]
我用oppo 4.4 的测没有问题，你再试试？可以换一个系统高一点的试一下

**Comment by youlookwhat** [comment]
恩，你在调调的，谢谢支持~
